version: "3.8"

services:
  redis-cluster:
      image: redis:latest
      container_name: redis_cluster
      command: redis-cli --cluster create localhost:7001 localhost:7002 localhost:7003 localhost:7004 localhost:7005 localhost:7006 --cluster-yes --cluster-replicas 1
      depends_on:
        - redis-master-1
        - redis-replica-1
        - redis-master-2
        - redis-replica-2
        - redis-master-3
        - redis-replica-3
      network_mode: "service:redis-master-1"

  redis-master-1:
    container_name: redis-master-1
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server /usr/local/etc/redis/redis.conf --port 7001 --protected-mode no
    restart: always
    ports:
      - "3306:3306"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"

  redis-replica-1:
    container_name: redis-replica-1
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master-1
    command: redis-server /usr/local/etc/redis/redis.conf --port 7002 --protected-mode no
    network_mode: "service:redis-master-1"
    depends_on:
      - redis-master-1
    restart: always

  redis-master-2:
    container_name: redis-master-2
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server /usr/local/etc/redis/redis.conf --port 7003 --protected-mode no
    network_mode: "service:redis-master-1"
    restart: always

  redis-replica-2:
    container_name: redis-replica-2
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master-2
    command: redis-server /usr/local/etc/redis/redis.conf --port 7004 --protected-mode no
    network_mode: "service:redis-master-1"
    depends_on:
      - redis-master-2
    restart: always

  redis-master-3:
      container_name: redis-master-3
      image: redis:latest
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - REDIS_REPLICATION_MODE=master
      command: redis-server /usr/local/etc/redis/redis.conf --port 7005 --protected-mode no
      network_mode: "service:redis-master-1"
      restart: always

  redis-replica-3:
    container_name: redis-replica-3
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master-3
    command: redis-server /usr/local/etc/redis/redis.conf --port 7006 --protected-mode no
    network_mode: "service:redis-master-1"
    depends_on:
      - redis-master-3
    restart: always
